version: "3"

# All available services
services:

  # Misc Storage
  postgres:
    container_name: "data-engine_postgres"
    restart: "always"
    image: postgres
    env_file:
      - ./config/postgres.env
    volumes:
      - ./db/:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  metabase:
    container_name: "data-engine_metabase"
    restart: "always"
    image: metabase/metabase
    env_file:
      - ./config/metabase_database.env
    volumes:
      - ./metabase:/metabase.db:cached
    ports:
      - 3000:3000